#pragma once

const int nMinCount = -0x11;

enum class FD_RESULT
{
    WARNING_NO_VIEDO_STREAM = nMinCount,
    WARNING_NO_AUDIO_STREAM,
    ERROR_NO_AUDIO_AND_VIEDO_STREAM,
    ERROR_ENCODER_FAIL_RECEIVE_PACKET,
    ERROR_ENCODER_FAIL_SEND_FRAME,
    ERROR_ENCODER_END_FILE,
    ERROR_ENCODER_FLUSH,
    OK,
};